services:
  esp-daemon:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO:-humble}
        USERNAME: ${DOCKER_USER:-ros}
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
        CONTAINER_TZ: ${CONTAINER_TZ:-Etc/UTC}
        DEFAULT_RMW_IMPLEMENTATION: ${DEFAULT_RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
    image: seanchangx/esp-daemon:${ROS_DISTRO:-humble}
    container_name: esp-daemon
    init: true
    stdin_open: true
    tty: true
    privileged: ${ESP_DAEMON_PRIVILEGED:-false}
    network_mode: host
    restart: unless-stopped
    working_dir: /home/${DOCKER_USER:-ros}/esp_daemon
    environment:
      TERM: xterm-256color
      TZ: ${TZ:-Etc/UTC}
      DISPLAY: ${DISPLAY:-}
      ROS_DISTRO: ${ROS_DISTRO:-humble}
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
      WS_DIR: /home/${DOCKER_USER:-ros}/esp_daemon
      MICRO_ROS_SERIAL_DEV: ${MICRO_ROS_SERIAL_DEV:-/dev/ttyACM0}
      AUTO_BOOTSTRAP_MICRO_ROS: ${AUTO_BOOTSTRAP_MICRO_ROS:-true}
      MICRO_ROS_INSTALL_ARGS: ${MICRO_ROS_INSTALL_ARGS:-}
    group_add:
      - dialout
    devices:
      - ${MICRO_ROS_SERIAL_DEV:-/dev/ttyACM0}:${MICRO_ROS_SERIAL_DEV:-/dev/ttyACM0}
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      # Mount app resources into container.
      - ./esp_daemon_ws:/home/${DOCKER_USER:-ros}/esp_daemon # ros2 workspace

      # Mount local timezone into container.
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    stop_grace_period: 10s

    entrypoint: ["/entrypoint.sh"]
